### ISSUE TITLE
XbaseIntegrationTest must use ISO-8859-1 encoding

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-extras#311]
In eclipse/xtext#1310 test failures on CJE CBI was detected when no system encoding is set. This leads to test failures in `XbaseIntegrationTest#testStringLiteral_06` and `XbaseIntegrationTest#testStringLiteral_07`:
```
java.lang.AssertionError: expected:<«> but was:<?>
```

To reproduce: Run XbaseIntegrationTest as JUnit test. Then open the created launch config and change the encoding on the Common tab to `US-ASCII` => Boom.

**Comment by kthoms** [comment]
We need a similar solution as we did today for KeywordHelperTest. @szarnekow can you help?

**Comment by kthoms** [comment]
This is a subtask for eclipse/xtext#1311

**Comment by szarnekow** [comment]
The problem appears to be org.eclipse.xtext.xbase.testing.CompilationTestHelper.copyToWorkspace(String, CharSequence) where the system encoding is used to write a file.

Here we should always write with UTF-8 and set a default load option on the resource set that is produced via unLoadedResourceSet and resourceSet so that all resources will know about the UTF-8 encoding.

**Comment by szarnekow** [comment]
Resolved
