### ISSUE TITLE
Type parameter in methods from generic interfaces are not translated correctly

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse/xtext-extras#559]
I got this XCore grammar in an XCore Project within Eclipse:

```
package test.genericstest

interface GenericClass<M> {
    op void foo(M m) {
        val M bar = m
        System.out.println(bar)
    }
}

class Implementer extends GenericClass<String> {
    
}
```
The xcore model does not have error markers, but the generated code has java errors. The foo() method in the generated ImplementerImpl looks like this:
```
public void foo(final String m) {
	final M bar = m;
	System.out.println(bar);
}
```
The parameter M here is replaced in the method parameters, however it is not replaced in the method body. I would either expect that the method foo in the generic class results in a method in an abstract class 'GenericClass' or that the method replaces the M correctly like this:
```
public void foo(final String m) {
	final String bar = m;
	System.out.println(bar);
}
```

**Comment by cdietrich** [comment]
cc @merks

**Comment by merks** [comment]
Yes, I can see that just won't work.  But that isn't just an Xcore problem, this is something that doesn't work with the EMF generator.  Xcore operation bodies are mapped to annotations in the induced Ecore model and the EMF generator will insert that text verbatim.   It doesn't seem feasible to transform the text being inserted because it would need to be parsed semantically to find the necessary replacements.  So the only way I could imagine this could be made to work is if the EMF generator was enhanced to support generating default methods in interfaces such that there is no need to insert/generate a copy of the body in various implementation classes.

Please open a Bugzilla:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EMF&component=Tools&version=2.21.0

That being said, the changes to support default operations/methods are very complex and pervasive.  It's unlikely I will tackle that without funding.

**Comment by NiklasRentzCAU** [comment]
The code body does seem to be parsed semantically as the 'val' keyword is also translated to 'final' in the Java code and the semicolons. If that is already done for the interface itself I can see the issue though.
For a workaround I just created a class with extension methods providing the same functionality as wanted by the generic method, so this is also not that important for me at the moment.

An issue in Bugzilla was created for documentation purposes.

**Comment by merks** [comment]
Yes, the XBase body is parsed and Java code is inferred, in the context of the interface where it is declared.  This textual body "snippet" is then recorded in the induced Ecore model  (as an annotation) so that it will be emitted when the "normal" EMF generator generates the Java code.   But the snippet only works in the context of the generic interface, and transforming it later is not feasible.

I'm happy that you have found a workaround.
