### ISSUE TITLE
Find clear way tho handle test projects need each other

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#7]

**Comment by meysholdt** [comment]
generally, test projects should not depend one another. That's because 
- we don't want to create deployable artifacts from test projects.
- tests may be moved into a src-folder inside the project of the code-under-test.

two options:
a) move the test utility into the test project. This may lead to redundancy, which is bad, it it's becoming too much
b) move the test utility into a test utility project, such as org.eclipse.xtext.testing. Here, however, we need to consider that we might *not* want to expose the utility class as API.

**Comment by cdietrich** [comment]
this effects test resources as well.

**Comment by meysholdt** [comment]
How many classes from one test project are actually used in a downstream-test-project?

**Comment by cdietrich** [comment]
i dont have an overview on this

- org.eclipse.xtext.purexbase.tests <5
- org.eclipse.xtext.java.tests 1

**Comment by cdietrich** [comment]
i pushed a first version of the resolution for the issue

**Comment by cdietrich** [comment]
closed with https://github.com/eclipse/xtext-extras/commit/bd0ad97418e783bcf4a01adeeed0ad24f7e0c077
