### ISSUE TITLE
Xtend bootstrapping

### ISSUE THREAD

**Issue by svenefftinge** [eclipse/xtext-extras#96]
We need to decide on a good strategy for when to apply the Xtend compiler. In the past we used to just check in the source code and told everyone to use the latest nightly for development. However we need to integrate the xtend compiler in the build to have proper source mapping in the resulting artifacts.

Automatically using the nightly will cause us trouble when someone breaks the xtend compiler accidentally. OTOH we want to use the latest state of the compiler and also want to have sensible turnaround times when fixing something in the compiler.

To the gradle build/experts would it be feasible to have a dedicated build job, where we use the latest successful build result as the bootstrap repository? That job should be parameterizable with a commit hash, so we can set it back in case something broke.

Additionally it would make sense to have one option in the build, that skips the xtend compiler all-together. At least as long as we keep checking in the generate source code this would be an easy way to bypass a broken compiler.

**Comment by spoenemann** [comment]
I created a build job that gathers the latest build results from the other build jobs (master branch) and publishes them locally. We can trigger this new job whenever we need to update the compiler.

http://services.typefox.io/open-source/jenkins/job/xtend-bootstrap/

The bootstrap repo is included with these PRs: eclipse/xtext-lib#35, eclipse/xtext-core#214, eclipse/xtext-extras#97, eclipse/xtext-web#29

With these changes you can also use the command line flag `-PskipXtendCompiler=true` to disable the Xtend compiler and use the checked in Java files from the xtend-gen folders instead.

**Comment by kthoms** [comment]
I guess this makes my PRs obsolete which applies the latest Xtend compiler output to xtend-gen?
Does this job recreate xtend-gen sources and check them in? Or do we make this manually?

**Comment by spoenemann** [comment]
The new job is just about providing a stable version to use for compiling. The contents of xtend-gen still need to be updated manually, either with the Eclipse builder or by running `./gradlew generateXtext`.

Even with the Xtend compiler in the build chain it is still important for us to keep generated Java files in version control in order to verify the consequences of changes to the compiler. However, we could consider removing the generated code from version control for those Xtext subprojects that are not in the classpath of the Xtend compiler, i.e. xtext-web and xtext-idea.

**Comment by kthoms** [comment]
Thanks for clarifying.

**Comment by spoenemann** [comment]
I think the current solution is sufficient for now. We can't reference specific commits in the xtend-bootstrap job, but at least we can delete builds if we see that they are corrupted.
